---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dahabore/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R style $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
